# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            Ove's Notes
tagline:          'Notes about This and That and Softwares'
description:      'Ove Bepari, An INTJ, CSE Undergrad Coder Who Usually Tries to Write Executable Poetry'
url:              https://ovebepari.github.io
baseurl:          ''

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

author:
  name: 'ovebepari'
  url: https://github.com/ovebepari
  twitter: "ovebepari"


# For a global message in the head
message: I'm running a <a href="https://ovebepari.github.io/personal/desktop-pc-campaign/">campaign</a>

exclude: []
