# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            Ove's Notes
tagline:          'Notes about this and that and softwares'
description:      'Ove Bepari, An INTJ, CSE Undergrad Coder Who Usually Writes Executable Poetry'
url:              https://ovebepari.github.io
baseurl:          ''          

plugins:
  - jekyll-seo-tag
  - jekyll-feed

author:
  name:           'ovebepari'
  url:            https://github.com/ovebepari


# For a global message in the head
message:
