# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            "DUETCS"
tagline:          'DUET Computer Society'
description:      'Working on bringing the tech skill gap and new world problem solving and addressing gap down, locally at DUET, Gazipur.'
url:              https://duetcs.github.io
baseurl:          ''

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

author:
  name: 'ovebepari'
  url: https://github.com/ovebepari
  twitter: "ovebepari"


# For a global message in the head
message:

exclude: []
