# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:            Ove's Notes
tagline:          'Notes about this and that and softwares'
description:      'An INTJ, CSE Undergrad Coder Who Writes Executable Poetry'
url:              https://github.com/ovebepari
baseurl:          

plugins:
  - jekyll-seo-tag

author:
  name:           'ovebepari'
  url:            https://github.com/ovebepari

paginate:         5
message:          